import fs from 'node:fs/promises'
import path from 'node:path'

const PROJECT_ROOT = process.cwd()
const PUBLIC_DIR = path.join(PROJECT_ROOT, 'public')
const ASSETS_DIR = path.join(PUBLIC_DIR, 'assets')
const OUTPUT_PATH = path.join(PROJECT_ROOT, 'src', 'data', 'assets.generated.js')

const ALLOWED_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp'])

const toAssetPath = (absolutePath) => {
  const relPath = path.relative(PUBLIC_DIR, absolutePath)
  return `/${relPath.split(path.sep).join('/')}`
}

const readDirSafe = async (dir) => {
  try {
    return await fs.readdir(dir, { withFileTypes: true })
  } catch (error) {
    if (error.code === 'ENOENT') return []
    throw error
  }
}

const listDirectories = async (dir) => {
  const entries = await readDirSafe(dir)
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b))
}

const listNumericImages = async (dir) => {
  const entries = await readDirSafe(dir)
  const files = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .map((name) => {
      const match = /^(\d+)(\.[^.]+)$/.exec(name)
      if (!match) return null
      const number = Number.parseInt(match[1], 10)
      const ext = match[2].toLowerCase()
      if (!Number.isFinite(number) || !ALLOWED_EXTENSIONS.has(ext)) return null
      return { name, number }
    })
    .filter(Boolean)
    .sort((a, b) => (a.number - b.number) || a.name.localeCompare(b.name))

  return files.map((file) => toAssetPath(path.join(dir, file.name)))
}

const findNamedImage = async (dir, baseName) => {
  const entries = await readDirSafe(dir)
  const matches = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => {
      const parsed = path.parse(name)
      return parsed.name.toLowerCase() === baseName
        && ALLOWED_EXTENSIONS.has(parsed.ext.toLowerCase())
    })
    .sort((a, b) => a.localeCompare(b))

  if (matches.length === 0) return ''
  return toAssetPath(path.join(dir, matches[0]))
}

const buildProjectAssets = async () => {
  const projectsDir = path.join(ASSETS_DIR, 'projects')
  const slugs = await listDirectories(projectsDir)
  const assets = {}

  for (const slug of slugs) {
    const projectDir = path.join(projectsDir, slug)
    const sliderDir = path.join(projectDir, 'slider')
    const beforeGalleryDir = path.join(projectDir, 'before-gallery')
    const afterGalleryDir = path.join(projectDir, 'after-gallery')

    assets[slug] = {
      sliderBefore: await findNamedImage(sliderDir, 'before'),
      sliderAfter: await findNamedImage(sliderDir, 'after'),
      beforeGallery: await listNumericImages(beforeGalleryDir),
      afterGallery: await listNumericImages(afterGalleryDir)
    }
  }

  return assets
}

const buildCollectionAssets = async () => {
  const collectionsDir = path.join(ASSETS_DIR, 'collections')
  const categories = await listDirectories(collectionsDir)
  const assets = {}

  for (const category of categories) {
    const categoryDir = path.join(collectionsDir, category)
    const ids = await listDirectories(categoryDir)
    assets[category] = {}

    for (const id of ids) {
      const itemDir = path.join(categoryDir, id)
      const images = await listNumericImages(itemDir)
      assets[category][id] = {
        cover: images[0] || '',
        images
      }
    }
  }

  return assets
}

const writeModule = async (projectAssets, collectionAssets) => {
  const contents = `// This file is generated by scripts/sync-assets.mjs.\n// Do not edit by hand.\nexport const projectAssetsBySlug = ${JSON.stringify(projectAssets, null, 2)}\n\nexport const collectionAssetsByCategory = ${JSON.stringify(collectionAssets, null, 2)}\n`

  await fs.writeFile(OUTPUT_PATH, contents, 'utf8')
}

const run = async () => {
  const projectAssets = await buildProjectAssets()
  const collectionAssets = await buildCollectionAssets()
  await writeModule(projectAssets, collectionAssets)
  console.log('Assets synced to src/data/assets.generated.js')
}

run().catch((error) => {
  console.error('Asset sync failed:', error)
  process.exit(1)
})
